package club.banyuan.view;

import sun.jvm.hotspot.asm.Register;

import javax.imageio.ImageIO;
import javax.swing.*;
import javax.swing.event.MouseInputAdapter;
import java.awt.*;
import java.awt.event.*;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;


public class Login extends javax.swing.JFrame {

    /**
     * Creates new form denglu
     */
    File file=new File("/Users/edz/project/OES/src/main/java/club/banyuan/view/picture/logo.png");
    BufferedImage bu;

    {
        try {
            bu = ImageIO.read(file);
        } catch (IOException e) {
            e.printStackTrace();
        }
    }

    Image image=bu;

    public Login() {
        initComponents();
        setLocationRelativeTo(null);
        setIconImage(bu);

    }
    static Login loginwin;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        用户身份 = new javax.swing.ButtonGroup();
        title = new javax.swing.JLabel();
        userName = new javax.swing.JLabel();
        login = new javax.swing.JButton();
        exit = new javax.swing.JButton();
        password = new javax.swing.JLabel();
        passwordInput = new javax.swing.JPasswordField();
        forgetPassword = new javax.swing.JLabel();
        remberPassword = new javax.swing.JCheckBox();
        askUser = new javax.swing.JLabel();
        userNameInput = new javax.swing.JComboBox<>();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        userName1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("考试系统");
        setAutoRequestFocus(false);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setLocation(new java.awt.Point(0, 0));
        setName("登陆界面"); // NOI18N
        setResizable(false);

        title.setFont(new java.awt.Font("Lucida Grande", 0, 28)); // NOI18N
        title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title.setText("半 圆 考 试 系 统");
        title.setToolTipText("");

        userName.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        userName.setText("用户名：");

        login.setText("登陆");
        login.setMaximumSize(new java.awt.Dimension(100, 30));
        login.setPreferredSize(new java.awt.Dimension(75, 32));
        login.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
//                JOptionPane.showMessageDialog(new javax.swing.JLabel(),"用户名或密码错误");
                passwordInput.setText("");
                String userNameTemp=(String) userNameInput.getEditor().getItem();
                System.out.println(userNameTemp);
                userNameInput.addItem(userNameTemp);
                if (true){
                    if (jRadioButton4.isSelected()) {
                        setVisible(false);
                        TestReady.start();
                    }
                    if (jRadioButton3.isSelected()){

                    }
                }
//                setVisible(false);
            }
        });

        exit.setText("退出");
        exit.setMaximumSize(new java.awt.Dimension(100, 30));
        exit.setPreferredSize(new java.awt.Dimension(75, 32));
        exit.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                System.exit(0);
            }
        });

        password.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        password.setText("密   码：");

        passwordInput.setPreferredSize(new java.awt.Dimension(200, 34));
        passwordInput.setSize(new java.awt.Dimension(200, 34));

        forgetPassword.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        forgetPassword.setText("忘记密码?");
        forgetPassword.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                JOptionPane.showMessageDialog(new javax.swing.JLabel(),"请联系管理员");
            }
        });

        remberPassword.setText("记住密码");

        askUser.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        askUser.setText("申请账号");
        askUser.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                RegisterOne.start();
                setVisible(false);
            }
        });

        userNameInput.setForeground(new java.awt.Color(255, 255, 255));
        userNameInput.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { }));
        userNameInput.setToolTipText("请输入用户名");
        userNameInput.setPreferredSize(new java.awt.Dimension(200, 34));
        userNameInput.setSize(new java.awt.Dimension(200, 34));
        userNameInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        userNameInput.setEditable(true);
        userNameInput.getEditor().getItem();

        用户身份.add(jRadioButton3);
        jRadioButton3.setText("管理员");

        用户身份.add(jRadioButton4);
        jRadioButton4.setText("学生");

        userName1.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        userName1.setText("身   份：");


        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap(120, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addGap(57, 57, 57)
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                                        .addGroup(layout.createSequentialGroup()
                                                                                .addComponent(login, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addGap(105, 105, 105))
                                                                        .addGroup(layout.createSequentialGroup()
                                                                                .addComponent(remberPassword)
                                                                                .addGap(18, 18, 18)
                                                                                .addComponent(askUser)
                                                                                .addGap(17, 17, 17)))
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(forgetPassword)
                                                                        .addComponent(exit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addGap(23, 23, 23)
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addGroup(layout.createSequentialGroup()
                                                                                .addComponent(userName1)
                                                                                .addGap(18, 18, 18)
                                                                                .addComponent(jRadioButton4)
                                                                                .addGap(43, 43, 43)
                                                                                .addComponent(jRadioButton3))
                                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                                                .addGroup(layout.createSequentialGroup()
                                                                                        .addComponent(userName)
                                                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                        .addComponent(userNameInput, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                                                .addGroup(layout.createSequentialGroup()
                                                                                        .addComponent(password)
                                                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                        .addComponent(passwordInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                                                .addGap(39, 39, 39)))
                                .addGap(111, 111, 111))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(34, 34, 34)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(userName)
                                        .addComponent(userNameInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(18, 18, 18)
                                                .addComponent(password))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(10, 10, 10)
                                                .addComponent(passwordInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jRadioButton3)
                                        .addComponent(jRadioButton4)
                                        .addComponent(userName1))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(forgetPassword)
                                        .addComponent(remberPassword)
                                        .addComponent(askUser))
                                .addGap(12, 12, 12)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(login, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(exit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(44, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                if (loginwin==null){
                synchronized (Login.class) {
                    if (loginwin == null) {
                        loginwin = new Login();
                        loginwin.setVisible(true);
                    }
                }
                }else {
                    loginwin.setVisible(true);
                }
            }
        });
    }

    // Variables declaration - do not modify
    private javax.swing.JLabel askUser;
    private javax.swing.JButton exit;
    private javax.swing.JLabel forgetPassword;
    private javax.swing.JComboBox<String> userNameInput;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JButton login;
    private javax.swing.JLabel password;
    private javax.swing.JPasswordField passwordInput;
    private javax.swing.JCheckBox remberPassword;
    private javax.swing.JLabel title;
    private javax.swing.JLabel userName;
    private javax.swing.JLabel userName1;
    private javax.swing.ButtonGroup 用户身份;
    // End of variables declaration
}