package club.banyuan.view;

import club.banyuan.service.AdminServer;
import club.banyuan.service.Impl.AdminServerImpl;
import javax.swing.*;
import java.awt.*;
import java.awt.event.*;



public class Login extends JFrame {


    AdminServer adminServer = new AdminServerImpl();

    /**
     * Creates new form denglu
//     */
//    File file=new File("/Users/edz/project/OES/src/main/java/club/banyuan/view/picture/logo.png");
//    BufferedImage bu;
//
//    {
//        try {
//            bu = ImageIO.read(file);
//        } catch (IOException e) {
//            e.printStackTrace();
//        }
//    }
//
//    Image image=bu;

    public Login() {
        initComponents();
        setLocationRelativeTo(null);
//        setIconImage(bu);

    }
    static Login loginwin;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        用户身份 = new ButtonGroup();
        title = new JLabel();
        userName = new JLabel();
        login = new JButton();
        exit = new JButton();
        password = new JLabel();
        passwordInput = new JPasswordField();
        forgetPassword = new JLabel();
        remberPassword = new JCheckBox();
        askUser = new JLabel();
        userNameInput = new JComboBox<>();
        jRadioButton3 = new JRadioButton();
        jRadioButton4 = new JRadioButton();
        userName1 = new JLabel();

        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        setTitle("考试系统");
        setAutoRequestFocus(false);
        setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
        setLocation(new Point(0, 0));
        setName("登陆界面"); // NOI18N
        setResizable(false);

        title.setFont(new Font("Lucida Grande", 0, 28)); // NOI18N
        title.setHorizontalAlignment(SwingConstants.CENTER);
        title.setText("半 圆 考 试 系 统");
        title.setToolTipText("");

        userName.setFont(new Font("Lucida Grande", 0, 16)); // NOI18N
        userName.setText("用户名：");

        login.setText("登陆");
        login.setMaximumSize(new Dimension(100, 30));
        login.setPreferredSize(new Dimension(75, 32));
        login.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                String userNameTemp=(String) userNameInput.getEditor().getItem();
                userNameInput.addItem(userNameTemp);
                if (true){
                    if (jRadioButton4.isSelected()) {
                        String uName = (String)userNameInput.getEditor().getItem();
                        String uPwd = new String(passwordInput.getPassword());

                        if(adminServer.login(uName,uPwd)){
                            setVisible(false);
                            TestReady.start();
                        }else {
                            JOptionPane.showMessageDialog(new javax.swing.JLabel(),"用户名和密码错误");
                        }
                    }
                    if (jRadioButton3.isSelected()){

                    }
                }
//                setVisible(false);
            }
        });

        exit.setText("退出");
        exit.setMaximumSize(new Dimension(100, 30));
        exit.setPreferredSize(new Dimension(75, 32));
        exit.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                System.exit(0);
            }
        });

        password.setFont(new Font("Lucida Grande", 0, 16)); // NOI18N
        password.setText("密   码：");

        passwordInput.setPreferredSize(new Dimension(200, 34));
        passwordInput.setSize(new Dimension(200, 34));

        forgetPassword.setFont(new Font("Lucida Grande", 0, 12)); // NOI18N
        forgetPassword.setText("忘记密码?");
        forgetPassword.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                JOptionPane.showMessageDialog(new JLabel(),"请联系管理员");
            }
        });

        remberPassword.setText("记住密码");

        askUser.setFont(new Font("Lucida Grande", 0, 12)); // NOI18N
        askUser.setText("申请账号");
        askUser.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                RegisterOne.start();
                setVisible(false);
            }
        });

        userNameInput.setForeground(new Color(255, 255, 255));
        userNameInput.setModel(new DefaultComboBoxModel<>(new String[] { }));
        userNameInput.setToolTipText("请输入用户名");
        userNameInput.setPreferredSize(new Dimension(200, 34));
        userNameInput.setSize(new Dimension(200, 34));
        userNameInput.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        userNameInput.setEditable(true);
        userNameInput.getEditor().getItem();

        用户身份.add(jRadioButton3);
        jRadioButton3.setText("管理员");

        用户身份.add(jRadioButton4);
        jRadioButton4.setText("学生");
        jRadioButton4.setSelected(true);

        userName1.setFont(new Font("Lucida Grande", 0, 16)); // NOI18N
        userName1.setText("身   份：");


        GroupLayout layout = new GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addGroup(GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap(120, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                        .addComponent(title, GroupLayout.PREFERRED_SIZE, 351, GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addGap(57, 57, 57)
                                                                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.TRAILING)
                                                                        .addGroup(layout.createSequentialGroup()
                                                                                .addComponent(login, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                                                                .addGap(105, 105, 105))
                                                                        .addGroup(layout.createSequentialGroup()
                                                                                .addComponent(remberPassword)
                                                                                .addGap(18, 18, 18)
                                                                                .addComponent(askUser)
                                                                                .addGap(17, 17, 17)))
                                                                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                                                        .addComponent(forgetPassword)
                                                                        .addComponent(exit, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)))
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addGap(23, 23, 23)
                                                                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                                                        .addGroup(layout.createSequentialGroup()
                                                                                .addComponent(userName1)
                                                                                .addGap(18, 18, 18)
                                                                                .addComponent(jRadioButton4)
                                                                                .addGap(43, 43, 43)
                                                                                .addComponent(jRadioButton3))
                                                                        .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING, false)
                                                                                .addGroup(layout.createSequentialGroup()
                                                                                        .addComponent(userName)
                                                                                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                                                                        .addComponent(userNameInput, 0, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                                                .addGroup(layout.createSequentialGroup()
                                                                                        .addComponent(password)
                                                                                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                                                                        .addComponent(passwordInput, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))))))
                                                .addGap(39, 39, 39)))
                                .addGap(111, 111, 111))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addComponent(title, GroupLayout.PREFERRED_SIZE, 82, GroupLayout.PREFERRED_SIZE)
                                .addGap(34, 34, 34)
                                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                        .addComponent(userName)
                                        .addComponent(userNameInput, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(18, 18, 18)
                                                .addComponent(password))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(10, 10, 10)
                                                .addComponent(passwordInput, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                        .addComponent(jRadioButton3)
                                        .addComponent(jRadioButton4)
                                        .addComponent(userName1))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                        .addComponent(forgetPassword)
                                        .addComponent(remberPassword)
                                        .addComponent(askUser))
                                .addGap(12, 12, 12)
                                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                        .addComponent(login, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                        .addComponent(exit, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(44, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>

    private void jComboBox1ActionPerformed(ActionEvent evt) {
        // TODO add your handling code here:
    }


    public static void startUI() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (UIManager.LookAndFeelInfo info : UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        EventQueue.invokeLater(new Runnable() {
            public void run() {
                if (loginwin==null){
                synchronized (Login.class) {
                    if (loginwin == null) {
                        loginwin = new Login();
                        loginwin.setVisible(true);
                    }
                }
                }else {
                    loginwin.setVisible(true);
                }
            }
        });
    }

    // Variables declaration - do not modify
    private JLabel askUser;
    private JButton exit;
    private JLabel forgetPassword;
    private JComboBox<String> userNameInput;
    private JRadioButton jRadioButton3;
    private JRadioButton jRadioButton4;
    private JButton login;
    private JLabel password;
    private JPasswordField passwordInput;
    private JCheckBox remberPassword;
    private JLabel title;
    private JLabel userName;
    private JLabel userName1;
    private ButtonGroup 用户身份;
    // End of variables declaration
}