package club.banyuan.view;

import club.banyuan.controller.CheckRegister;
import club.banyuan.dao.AdminDaoImpl;
import club.banyuan.dao.IAdminDao;
import club.banyuan.dao.IQuestionDao;
import club.banyuan.dao.QuestionDaoImpl;
import club.banyuan.pojo.Question;
import club.banyuan.pojo.Student;

import javax.swing.*;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.event.MenuEvent;
import javax.swing.event.MenuListener;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.Map;

public class Manage extends JFrame {

    static  IAdminDao adminDao = new AdminDaoImpl();
    static IQuestionDao questionDao  = new QuestionDaoImpl();

    /**
     * Creates new form 考试
     */
    public Manage() {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
    }
static Manage manage;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jFrame1 = new JFrame();
        jLabel1 = new JLabel();
        jTextField2 = new JTextField();
        jTextField3 = new JTextField();
        jLabel3 = new JLabel();
        jTextField4 = new JTextField();
        jLabel4 = new JLabel();
        jTextField5 = new JTextField();
        jLabel5 = new JLabel();
        jButton4 = new JButton();
        jButton5 = new JButton();
        jLabel10 = new JLabel();
        jFrame3 = new JFrame();
        jLabel11 = new JLabel();
        jTextField10 = new JTextField();
        jTextField11 = new JTextField();
        jLabel12 = new JLabel();
        jTextField12 = new JTextField();
        jLabel13 = new JLabel();
        jTextField13 = new JTextField();
        jLabel14 = new JLabel();
        jButton8 = new JButton();
        jButton9 = new JButton();
        jLabel15 = new JLabel();
        jFrame4 = new JFrame();
        jLabel16 = new JLabel();
        jTextField14 = new JTextField();
        jTextField15 = new JTextField();
        jLabel17 = new JLabel();
        jButton11 = new JButton();
        jButton12 = new JButton();
        jLabel20 = new JLabel();
        jFrame5 = new JFrame();
        jLabel21 = new JLabel();
        jTextField18 = new JTextField();
        jTextField19 = new JTextField();
        jLabel22 = new JLabel();
        jTextField20 = new JTextField();
        jLabel23 = new JLabel();
        jTextField21 = new JTextField();
        jLabel24 = new JLabel();
        jButton13 = new JButton();
        jButton14 = new JButton();
        jLabel25 = new JLabel();
        jFrame6 = new JFrame();
        jButton18 = new JButton();
        jButton19 = new JButton();
        jLabel2 = new JLabel();
        jTextField1 = new JTextField();
        jFrame2 = new JFrame();
        jFileChooser1 = new JFileChooser();
        jFrame8 = new JFrame();
        jTextField23 = new JTextField();
        jLabel28 = new JLabel();
        jButton17 = new JButton();
        jButton20 = new JButton();
        jLabel29 = new JLabel();
        jPanel3 = new JPanel();
        jLabel6 = new JLabel();
        jScrollPane2 = new JScrollPane();
        jTextArea1 = new JTextArea();
        jButton1 = new JButton();
        jPanel4 = new JPanel();
        jLabel7 = new JLabel();
        nameInput = new JTextField();
        inquireBatton = new JButton();
        studentShow = new JScrollPane();
        jList2 = new JList<>();
        fixBatton = new JButton();
        delBatton = new JButton();
        jPanel2 = new JPanel();
        jScrollPane1 = new JScrollPane();
        jList1 = new JList<>();
        jScrollPane4 = new JScrollPane();
        jTextArea2 = new JTextArea();
        jPanel5 = new JPanel();
        jLabel8 = new JLabel();
        subjectInput = new JTextField();
        inquireBatton2 = new JButton();
        jScrollPane5 = new JScrollPane();
        jList3 = new JList<>();
        fixBatton2 = new JButton();
        delBatton2 = new JButton();
        jMenuBar1 = new JMenuBar();
        jMenu5 = new JMenu();
        jMenu1 = new JMenu();
        jMenu4 = new JMenu();
        jMenuItem2 = new JMenuItem();
        jMenuItem7 = new JMenuItem();
        jMenuItem1 = new JMenuItem();
        jMenu2 = new JMenu();
        jMenuItem10 = new JMenuItem();
        jMenu7 = new JMenu();
        jMenuItem4 = new JMenuItem();
        jMenuItem6 = new JMenuItem();
        jMenuItem8 = new JMenuItem();
        jMenuItem9=new JMenuItem();

        jFrame1.setResizable(false);
        jFrame1.setLocationRelativeTo(null);
        jFrame1.setSize(321,359);
        jFrame2.setResizable(false);
        jFrame2.setLocationRelativeTo(null);
        jFrame2.setSize(562,412);
        jFrame3.setResizable(false);
        jFrame3.setLocationRelativeTo(null);
        jFrame3.setSize(321,359);
        jFrame4.setResizable(false);
        jFrame4.setLocationRelativeTo(null);
        jFrame4.setSize(321,359);
        jFrame5.setResizable(false);
        jFrame5.setLocationRelativeTo(null);
        jFrame5.setSize(321,359);
        jFrame6.setResizable(false);
        jFrame6.setLocationRelativeTo(null);
        jFrame6.setSize(364,230);
        jFrame8.setResizable(false);
        jFrame8.setLocationRelativeTo(null);
        jFrame8.setSize(321,261);



        jPanel2.setVisible(false);
        jPanel4.setVisible(false);
        jPanel5.setVisible(false);
        jPanel3.setVisible(true);

        jLabel1.setText("ID:");

        jTextField2.setEnabled(false);

        jTextField3.setText("");
        jTextField3.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });

        jLabel3.setText("用户名：");

        jTextField4.setText("");

        jLabel4.setText("姓  名：");

        jTextField5.setText("");

        jLabel5.setText("密  码：");

        jButton4.setText("确认");
        jButton4.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {


                if (CheckRegister.checkUserName(jTextField3.getText())&&CheckRegister.checkName(jTextField3.getText())&&CheckRegister.checkPwd(jTextField5.getText())) {           //-------------------------------验证码没有
                    JOptionPane.showMessageDialog(new JLabel(), "更改成功");
                    jFrame1.setVisible(false);
                    setVisible(true);
                } else {
                    JOptionPane.showMessageDialog(new JLabel(), "输入格式错误");
                }
            }
        });

        jButton5.setText("取消");
        jButton5.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                jFrame1.setVisible(false);
                setVisible(true);
            }
        });

        jLabel10.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jLabel10.setHorizontalAlignment(SwingConstants.CENTER);
        jLabel10.setText("修改信息");

        GroupLayout jFrame1Layout = new GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
                jFrame1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addGroup(GroupLayout.Alignment.TRAILING, jFrame1Layout.createSequentialGroup()
                                .addContainerGap(65, Short.MAX_VALUE)
                                .addGroup(jFrame1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                        .addGroup(jFrame1Layout.createSequentialGroup()
                                                .addComponent(jLabel3)
                                                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jTextField3, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jFrame1Layout.createSequentialGroup()
                                                .addComponent(jLabel4)
                                                .addGap(18, 18, 18)
                                                .addComponent(jTextField4, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jFrame1Layout.createSequentialGroup()
                                                .addComponent(jLabel5)
                                                .addGap(18, 18, 18)
                                                .addComponent(jTextField5, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jFrame1Layout.createSequentialGroup()
                                                .addComponent(jLabel1)
                                                .addGap(48, 48, 48)
                                                .addComponent(jTextField2, GroupLayout.PREFERRED_SIZE, 136, GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jFrame1Layout.createSequentialGroup()
                                                .addComponent(jButton4)
                                                .addGap(43, 43, 43)
                                                .addComponent(jButton5)))
                                .addGap(54, 54, 54))
                        .addGroup(jFrame1Layout.createSequentialGroup()
                                .addGap(88, 88, 88)
                                .addComponent(jLabel10, GroupLayout.PREFERRED_SIZE, 145, GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jFrame1Layout.linkSize(SwingConstants.HORIZONTAL, new java.awt.Component[] {jTextField2, jTextField3, jTextField4, jTextField5});

        jFrame1Layout.setVerticalGroup(
                jFrame1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addGroup(GroupLayout.Alignment.TRAILING, jFrame1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel10, GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jFrame1Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel1)
                                        .addComponent(jTextField2, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jFrame1Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel3)
                                        .addComponent(jTextField3, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jFrame1Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel4)
                                        .addComponent(jTextField4, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jFrame1Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel5)
                                        .addComponent(jTextField5, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                                .addGap(34, 34, 34)
                                .addGroup(jFrame1Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                        .addComponent(jButton4)
                                        .addComponent(jButton5))
                                .addGap(27, 27, 27))
        );

        jLabel11.setText("ID:");

        jTextField10.setEnabled(false);

        jTextField11.setText("");
        jTextField11.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                jTextField11ActionPerformed(evt);
            }
        });

        jLabel12.setText("用户名：");

        jTextField12.setText("");

        jLabel13.setText("姓  名：");

        jTextField13.setText("");

        jLabel14.setText("密  码：");

        jButton8.setText("确认");
        jButton8.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                if (CheckRegister.checkUserName(jTextField11.getText())&&CheckRegister.checkName(jTextField12.getText())&&CheckRegister.checkPwd(jTextField13.getText())) {
                    System.out.println(jTextField11.getText()+ "  "+ jTextField13.getText());
                    adminDao.insertUser(jTextField11.getText(),jTextField12.getText(),jTextField13.getText());
                    JOptionPane.showMessageDialog(new JLabel(), "添加成功");
                    jFrame3.setVisible(false);
                    setVisible(true);
                } else {
                    JOptionPane.showMessageDialog(new JLabel(), "输入格式错误");
                }
            }
        });

        jButton9.setText("取消");
        jButton9.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                jFrame3.setVisible(false);
                setVisible(true);
            }
        });

        jLabel15.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jLabel15.setHorizontalAlignment(SwingConstants.CENTER);
        jLabel15.setText("添加学员");

        GroupLayout jFrame3Layout = new GroupLayout(jFrame3.getContentPane());
        jFrame3.getContentPane().setLayout(jFrame3Layout);
        jFrame3Layout.setHorizontalGroup(
                jFrame3Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addGroup(GroupLayout.Alignment.TRAILING, jFrame3Layout.createSequentialGroup()
                                .addContainerGap(65, Short.MAX_VALUE)
                                .addGroup(jFrame3Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                        .addGroup(jFrame3Layout.createSequentialGroup()
                                                .addComponent(jLabel12)
                                                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jTextField11, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jFrame3Layout.createSequentialGroup()
                                                .addComponent(jLabel13)
                                                .addGap(18, 18, 18)
                                                .addComponent(jTextField12, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jFrame3Layout.createSequentialGroup()
                                                .addComponent(jLabel14)
                                                .addGap(18, 18, 18)
                                                .addComponent(jTextField13, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jFrame3Layout.createSequentialGroup()
                                                .addComponent(jLabel11)
                                                .addGap(48, 48, 48)
                                                .addComponent(jTextField10, GroupLayout.PREFERRED_SIZE, 136, GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jFrame3Layout.createSequentialGroup()
                                                .addComponent(jButton8)
                                                .addGap(43, 43, 43)
                                                .addComponent(jButton9)))
                                .addGap(54, 54, 54))
                        .addGroup(jFrame3Layout.createSequentialGroup()
                                .addGap(88, 88, 88)
                                .addComponent(jLabel15, GroupLayout.PREFERRED_SIZE, 145, GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jFrame3Layout.linkSize(SwingConstants.HORIZONTAL, new java.awt.Component[] {jTextField10, jTextField11, jTextField12, jTextField13});

        jFrame3Layout.setVerticalGroup(
                jFrame3Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addGroup(GroupLayout.Alignment.TRAILING, jFrame3Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel15, GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jFrame3Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel11)
                                        .addComponent(jTextField10, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jFrame3Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel12)
                                        .addComponent(jTextField11, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jFrame3Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel13)
                                        .addComponent(jTextField12, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jFrame3Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel14)
                                        .addComponent(jTextField13, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                                .addGap(34, 34, 34)
                                .addGroup(jFrame3Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                        .addComponent(jButton8)
                                        .addComponent(jButton9))
                                .addGap(27, 27, 27))
        );

        jLabel16.setText("ID:");

        jTextField14.setEnabled(false);

        jTextField15.setText("");
        jTextField15.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                jTextField15ActionPerformed(evt);
            }
        });

        jLabel17.setText("课程名称：");

        jButton11.setText("确认");
        jButton11.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                JOptionPane.showMessageDialog(new JLabel(), "添加成功");
                jFrame4.setVisible(false);
                setVisible(true);
            }
        });

        jButton12.setText("取消");
        jButton12.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                jFrame4.setVisible(false);
                setVisible(true);
            }
        });

        jLabel20.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jLabel20.setHorizontalAlignment(SwingConstants.CENTER);
        jLabel20.setText("添加课程");

        GroupLayout jFrame4Layout = new GroupLayout(jFrame4.getContentPane());
        jFrame4.getContentPane().setLayout(jFrame4Layout);
        jFrame4Layout.setHorizontalGroup(
                jFrame4Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addGroup(GroupLayout.Alignment.TRAILING, jFrame4Layout.createSequentialGroup()
                                .addContainerGap(65, Short.MAX_VALUE)
                                .addGroup(jFrame4Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                        .addGroup(jFrame4Layout.createSequentialGroup()
                                                .addComponent(jLabel17)
                                                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jTextField15, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jFrame4Layout.createSequentialGroup()
                                                .addComponent(jLabel16)
                                                .addGap(48, 48, 48)
                                                .addComponent(jTextField14, GroupLayout.PREFERRED_SIZE, 136, GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jFrame4Layout.createSequentialGroup()
                                                .addComponent(jButton11)
                                                .addGap(43, 43, 43)
                                                .addComponent(jButton12)))
                                .addGap(54, 54, 54))
                        .addGroup(jFrame4Layout.createSequentialGroup()
                                .addGap(88, 88, 88)
                                .addComponent(jLabel20, GroupLayout.PREFERRED_SIZE, 145, GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jFrame4Layout.linkSize(SwingConstants.HORIZONTAL, new java.awt.Component[] {jTextField14, jTextField15});

        jFrame4Layout.setVerticalGroup(
                jFrame4Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addGroup(GroupLayout.Alignment.TRAILING, jFrame4Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel20, GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addGroup(jFrame4Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel16)
                                        .addComponent(jTextField14, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                                .addGap(28, 28, 28)
                                .addGroup(jFrame4Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel17)
                                        .addComponent(jTextField15, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                                .addGap(60, 60, 60)
                                .addGroup(jFrame4Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                        .addComponent(jButton11)
                                        .addComponent(jButton12))
                                .addGap(67, 67, 67))
        );

        jLabel21.setText("ID:");

        jTextField18.setEnabled(false);

        jTextField19.setText("");


        jLabel22.setText("所属课程：");

        jTextField20.setText("");


        jLabel23.setText("题目内容：");

        jTextField21.setText("");

        jLabel24.setText("选项类型：");

        jButton13.setText("确认");
        jButton13.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                JOptionPane.showMessageDialog(new JLabel(), "添加成功");
                jFrame5.setVisible(false);
                setVisible(true);
            }
        });

        jButton14.setText("取消");
        jButton14.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                jFrame5.setVisible(false);
                setVisible(true);
            }
        });

        jLabel25.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jLabel25.setHorizontalAlignment(SwingConstants.CENTER);
        jLabel25.setText("添加题目");

        GroupLayout jFrame5Layout = new GroupLayout(jFrame5.getContentPane());
        jFrame5.getContentPane().setLayout(jFrame5Layout);
        jFrame5Layout.setHorizontalGroup(
                jFrame5Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addGroup(GroupLayout.Alignment.TRAILING, jFrame5Layout.createSequentialGroup()
                                .addContainerGap(48, Short.MAX_VALUE)
                                .addGroup(jFrame5Layout.createParallelGroup(GroupLayout.Alignment.LEADING, false)
                                        .addGroup(jFrame5Layout.createSequentialGroup()
                                                .addComponent(jLabel24)
                                                .addGap(18, 18, 18)
                                                .addComponent(jTextField21, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jFrame5Layout.createSequentialGroup()
                                                .addComponent(jButton13)
                                                .addGap(43, 43, 43)
                                                .addComponent(jButton14))
                                        .addGroup(jFrame5Layout.createSequentialGroup()
                                                .addGroup(jFrame5Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel22)
                                                        .addComponent(jLabel21))
                                                .addGroup(jFrame5Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                                        .addGroup(jFrame5Layout.createSequentialGroup()
                                                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                .addComponent(jTextField18, GroupLayout.PREFERRED_SIZE, 136, GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(jFrame5Layout.createSequentialGroup()
                                                                .addGap(18, 18, 18)
                                                                .addComponent(jTextField19, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))))
                                        .addGroup(jFrame5Layout.createSequentialGroup()
                                                .addComponent(jLabel23)
                                                .addGap(18, 18, 18)
                                                .addComponent(jTextField20, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)))
                                .addGap(54, 54, 54))
                        .addGroup(jFrame5Layout.createSequentialGroup()
                                .addGap(88, 88, 88)
                                .addComponent(jLabel25, GroupLayout.PREFERRED_SIZE, 145, GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jFrame5Layout.linkSize(SwingConstants.HORIZONTAL, new java.awt.Component[] {jTextField18, jTextField19, jTextField20, jTextField21});

        jFrame5Layout.setVerticalGroup(
                jFrame5Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addGroup(GroupLayout.Alignment.TRAILING, jFrame5Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel25, GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jFrame5Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel21)
                                        .addComponent(jTextField18, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jFrame5Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel22)
                                        .addComponent(jTextField19, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jFrame5Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel23)
                                        .addComponent(jTextField20, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jFrame5Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel24)
                                        .addComponent(jTextField21, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                                .addGap(34, 34, 34)
                                .addGroup(jFrame5Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                        .addComponent(jButton13)
                                        .addComponent(jButton14))
                                .addGap(27, 27, 27))
        );

        jButton18.setText("确认");
        jButton18.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                JOptionPane.showMessageDialog(new JLabel(), "密码修改成功");
                jFrame6.setVisible(false);
                setVisible(true);
            }
        });

        jButton19.setText("取消");
        jButton19.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                jFrame6.setVisible(false);
                setVisible(true);
            }
        });

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        jLabel2.setHorizontalAlignment(SwingConstants.CENTER);
        jLabel2.setText("请输入新密码");

        jTextField1.setText("");


        GroupLayout jFrame6Layout = new GroupLayout(jFrame6.getContentPane());
        jFrame6.getContentPane().setLayout(jFrame6Layout);
        jFrame6Layout.setHorizontalGroup(
                jFrame6Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addGroup(jFrame6Layout.createSequentialGroup()
                                .addContainerGap(87, Short.MAX_VALUE)
                                .addGroup(jFrame6Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                        .addGroup(GroupLayout.Alignment.TRAILING, jFrame6Layout.createSequentialGroup()
                                                .addComponent(jButton18)
                                                .addGap(43, 43, 43)
                                                .addComponent(jButton19)
                                                .addGap(84, 84, 84))
                                        .addGroup(GroupLayout.Alignment.TRAILING, jFrame6Layout.createSequentialGroup()
                                                .addComponent(jLabel2, GroupLayout.PREFERRED_SIZE, 144, GroupLayout.PREFERRED_SIZE)
                                                .addGap(109, 109, 109))
                                        .addGroup(GroupLayout.Alignment.TRAILING, jFrame6Layout.createSequentialGroup()
                                                .addComponent(jTextField1, GroupLayout.PREFERRED_SIZE, 168, GroupLayout.PREFERRED_SIZE)
                                                .addGap(95, 95, 95))))
        );
        jFrame6Layout.setVerticalGroup(
                jFrame6Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addGroup(GroupLayout.Alignment.TRAILING, jFrame6Layout.createSequentialGroup()
                                .addGap(46, 46, 46)
                                .addComponent(jLabel2, GroupLayout.PREFERRED_SIZE, 41, GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28)
                                .addComponent(jTextField1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                                .addGroup(jFrame6Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                        .addComponent(jButton18)
                                        .addComponent(jButton19))
                                .addGap(29, 29, 29))
        );

        GroupLayout jFrame2Layout = new GroupLayout(jFrame2.getContentPane());
        jFrame2.getContentPane().setLayout(jFrame2Layout);
        jFrame2Layout.setHorizontalGroup(
                jFrame2Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addGroup(jFrame2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jFileChooser1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jFrame2Layout.setVerticalGroup(
                jFrame2Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addGroup(jFrame2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jFileChooser1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTextField23.setText("");

        jLabel28.setText("课程名称：");

        jButton17.setText("确认");
        jButton17.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                JOptionPane.showMessageDialog(new JLabel(), "删除成功");
                jFrame8.setVisible(false);
                setVisible(true);
            }
        });

        jButton20.setText("取消");
        jButton20.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                jFrame8.setVisible(false);
                setVisible(true);
            }
        });

        jLabel29.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jLabel29.setHorizontalAlignment(SwingConstants.CENTER);
        jLabel29.setText("删除课程");

        GroupLayout jFrame8Layout = new GroupLayout(jFrame8.getContentPane());
        jFrame8.getContentPane().setLayout(jFrame8Layout);
        jFrame8Layout.setHorizontalGroup(
                jFrame8Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addGroup(jFrame8Layout.createSequentialGroup()
                                .addContainerGap(65, Short.MAX_VALUE)
                                .addGroup(jFrame8Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                        .addGroup(GroupLayout.Alignment.TRAILING, jFrame8Layout.createSequentialGroup()
                                                .addGroup(jFrame8Layout.createParallelGroup(GroupLayout.Alignment.LEADING, false)
                                                        .addGroup(jFrame8Layout.createSequentialGroup()
                                                                .addComponent(jLabel28)
                                                                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                                                                .addComponent(jTextField23))
                                                        .addGroup(jFrame8Layout.createSequentialGroup()
                                                                .addComponent(jButton17)
                                                                .addGap(43, 43, 43)
                                                                .addComponent(jButton20)))
                                                .addGap(63, 63, 63))
                                        .addGroup(GroupLayout.Alignment.TRAILING, jFrame8Layout.createSequentialGroup()
                                                .addComponent(jLabel29, GroupLayout.PREFERRED_SIZE, 145, GroupLayout.PREFERRED_SIZE)
                                                .addGap(86, 86, 86))))
        );
        jFrame8Layout.setVerticalGroup(
                jFrame8Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addGroup(GroupLayout.Alignment.TRAILING, jFrame8Layout.createSequentialGroup()
                                .addGap(60, 60, 60)
                                .addComponent(jLabel29, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(44, 44, 44)
                                .addGroup(jFrame8Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel28)
                                        .addComponent(jTextField23, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                                .addGap(34, 34, 34)
                                .addGroup(jFrame8Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                        .addComponent(jButton17)
                                        .addComponent(jButton20))
                                .addGap(38, 38, 38))
        );
        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);

        jLabel6.setText(Login.atrueName);
        jLabel6.setFont(new Font("宋体",Font.BOLD,30));

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        jButton1.setText("更换头像");

        GroupLayout jPanel3Layout = new GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
                jPanel3Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addGroup(GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addContainerGap(53, Short.MAX_VALUE)
                                .addGroup(jPanel3Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                        .addGroup(GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                                .addComponent(jLabel6, GroupLayout.PREFERRED_SIZE, 175, GroupLayout.PREFERRED_SIZE)
                                                .addGap(30, 30, 30))
                                        .addGroup(GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                                .addComponent(jButton1)
                                                .addGap(73, 73, 73)))
                                .addComponent(jScrollPane2, GroupLayout.PREFERRED_SIZE, 231, GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28))
        );
        jPanel3Layout.setVerticalGroup(
                jPanel3Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                                .addContainerGap(40, Short.MAX_VALUE)
                                .addGroup(jPanel3Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                        .addGroup(GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                                .addComponent(jLabel6, GroupLayout.PREFERRED_SIZE, 158, GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(jButton1)
                                                .addGap(37, 37, 37))
                                        .addGroup(GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                                .addComponent(jScrollPane2, GroupLayout.PREFERRED_SIZE, 262, GroupLayout.PREFERRED_SIZE)
                                                .addGap(36, 36, 36))))
        );

        jLabel7.setText("请输入学生姓名：");

        nameInput.setText("");

        inquireBatton.setText("查询");
        inquireBatton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                List<Student> list = adminDao.selectStudentByName(nameInput.getText());
                if(list.size() == 0){
                    JOptionPane.showMessageDialog(new Label(),"查无此人");
                }else {
                    Student student = list.get(0);
                    DefaultListModel dlm=new DefaultListModel();
                    dlm.addElement(student.toString());
                    jList2.setModel(dlm);
                }
            }
        });

        final  List<Student> students = adminDao.selectAllStudent();
        DefaultListModel dlmPre=new DefaultListModel();

        for (Student student : students) {
            dlmPre.addElement(student.toString());
        }
        jList2.setModel(dlmPre);




       /* jList2.setModel(new AbstractListModel<String>() {
           // IAdminDao adminDao = new AdminDaoImpl();
         //   String[] strings = { students.get.toString(), "Item 2", "Item 3", "Item 4", "Item 5", "Item 5", "Item 5", "Item 5", "Item 5", "Item 5Item 5", "Item 5", "Item 5", "Item 5", "Item 5Item 5", "Item 5", "Item 5", "Item 5", "Item 5", "Item 5", "Item 5", "Item 5", "Item 5", "Item 5", " " };
           // public int getSize() { return strings.length; }
        //    public String getElementAt(int i) { return strings[i]; }
        });*/
        studentShow.setViewportView(jList2);

        fixBatton.setText("修改");
        fixBatton.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                setVisible(false);
                jFrame1.setVisible(true);
            }
        });

        delBatton.setText("删除");
        delBatton.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                if(adminDao.selectStudentByName(nameInput.getText()) != null){
                    adminDao.delStudent(nameInput.getText());
                    JOptionPane.showMessageDialog(new JLabel(), "删除成功");
                    final  List<Student> students = adminDao.selectAllStudent();
                    DefaultListModel dlmPre=new DefaultListModel();

                    for (Student student : students) {
                        dlmPre.addElement(student.toString());
                    }
                    jList2.setModel(dlmPre);

                }else {
                    JOptionPane.showMessageDialog(new JLabel(), "查无此人");
                }
            }
        });

        GroupLayout jPanel4Layout = new GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
                jPanel4Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addGroup(GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addContainerGap(55, Short.MAX_VALUE)
                                .addGroup(jPanel4Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel4Layout.createParallelGroup(GroupLayout.Alignment.LEADING, false)
                                                .addComponent(studentShow)
                                                .addGroup(jPanel4Layout.createSequentialGroup()
                                                        .addComponent(jLabel7, GroupLayout.PREFERRED_SIZE, 116, GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                                                        .addComponent(nameInput, GroupLayout.PREFERRED_SIZE, 188, GroupLayout.PREFERRED_SIZE)
                                                        .addGap(30, 30, 30)
                                                        .addComponent(inquireBatton)))
                                        .addGroup(jPanel4Layout.createSequentialGroup()
                                                .addGap(97, 97, 97)
                                                .addComponent(fixBatton)
                                                .addGap(60, 60, 60)
                                                .addComponent(delBatton)))
                                .addGap(45, 45, 45))
        );
        jPanel4Layout.setVerticalGroup(
                jPanel4Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addGroup(GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addContainerGap(43, Short.MAX_VALUE)
                                .addGroup(jPanel4Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel7, GroupLayout.PREFERRED_SIZE, 32, GroupLayout.PREFERRED_SIZE)
                                        .addComponent(nameInput, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                        .addComponent(inquireBatton))
                                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(studentShow, GroupLayout.PREFERRED_SIZE, 182, GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel4Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                        .addComponent(fixBatton)
                                        .addComponent(delBatton))
                                .addGap(27, 27, 27))
        );


        jScrollPane1.setViewportView(jList1);
        jList1.addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent e) {
                List<Student> list = adminDao.selectStudentByNameAndScore(jList1.getSelectedValue());
                String point = "";
                for (Map.Entry<String, Double> stringDoubleEntry : list.get(0).getScore().entrySet()) {
                    point += stringDoubleEntry.getKey() + " : " + stringDoubleEntry.getValue() + "\n";
                }
                jTextArea2.setText(point);
            }
        });
        jTextArea1.setFont(new Font("宋体",Font.BOLD,100));
        jTextArea1.setText("牛" + "\n" + "逼");
/*
        List<Student> list = new
        DefaultListModel dlm=new DefaultListModel();
        dlm.addElement();*/


        jTextArea2.setColumns(20);
        jTextArea2.setLineWrap(true);
        jTextArea2.setRows(5);
        jTextArea2.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jScrollPane4.setViewportView(jTextArea2);

        GroupLayout jPanel2Layout = new GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
                jPanel2Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(jScrollPane1, GroupLayout.PREFERRED_SIZE, 271, GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane4, GroupLayout.PREFERRED_SIZE, 198, GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(25, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
                jPanel2Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addGroup(jPanel2Layout.createParallelGroup(GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jScrollPane1)
                                        .addComponent(jScrollPane4, GroupLayout.PREFERRED_SIZE, 289, GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(33, Short.MAX_VALUE))
        );

        jLabel8.setText("请输入题目编号：");

        subjectInput.setText("");

        inquireBatton2.setText("查询");
        inquireBatton2.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
            }
        });



        DefaultListModel defaultListModel = new DefaultListModel();
        List<Question> list = questionDao.selectAllQuestion();
        for (Question question : list) {
            defaultListModel.addElement(question);
        }
        jList3.setModel(defaultListModel);


        jScrollPane5.setViewportView(jList3);

        fixBatton2.setText("添加");
        fixBatton2.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                setVisible(false);
                jFrame5.setVisible(true);
            }
        });

        delBatton2.setText("删除");
        delBatton2.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                JOptionPane.showMessageDialog(new JLabel(), "删除成功");
            }
        });

        GroupLayout jPanel5Layout = new GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
                jPanel5Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addGroup(GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                                .addContainerGap(55, Short.MAX_VALUE)
                                .addGroup(jPanel5Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel5Layout.createParallelGroup(GroupLayout.Alignment.LEADING, false)
                                                .addComponent(jScrollPane5)
                                                .addGroup(jPanel5Layout.createSequentialGroup()
                                                        .addComponent(jLabel8, GroupLayout.PREFERRED_SIZE, 116, GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                                                        .addComponent(subjectInput, GroupLayout.PREFERRED_SIZE, 188, GroupLayout.PREFERRED_SIZE)
                                                        .addGap(30, 30, 30)
                                                        .addComponent(inquireBatton2)))
                                        .addGroup(jPanel5Layout.createSequentialGroup()
                                                .addGap(97, 97, 97)
                                                .addComponent(fixBatton2)
                                                .addGap(60, 60, 60)
                                                .addComponent(delBatton2)))
                                .addGap(49, 49, 49))
        );
        jPanel5Layout.setVerticalGroup(
                jPanel5Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addGroup(jPanel5Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel8, GroupLayout.PREFERRED_SIZE, 32, GroupLayout.PREFERRED_SIZE)
                                        .addComponent(subjectInput, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                        .addComponent(inquireBatton2))
                                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane5, GroupLayout.PREFERRED_SIZE, 182, GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel5Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                        .addComponent(fixBatton2)
                                        .addComponent(delBatton2))
                                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jMenuBar1.setSize(new java.awt.Dimension(86, 30));

        jMenu5.setText("首页");
        jMenuBar1.add(jMenu5);
        jMenu5.addMenuListener(new MenuListener() {
            @Override
            public void menuSelected(MenuEvent e) {
                jPanel3.setVisible(true);
                jPanel4.setVisible(false);
                jPanel2.setVisible(false);
                jPanel5.setVisible(false);
            }

            @Override
            public void menuDeselected(MenuEvent e) {

            }

            @Override
            public void menuCanceled(MenuEvent e) {

            }
        });

        jMenu1.setText("学生管理");
        jMenu1.setPreferredSize(new java.awt.Dimension(74, 30));


        jMenu4.setText("学生信息");

        jMenuItem2.setText("增加学员");
        jMenu4.add(jMenuItem2);
        jMenuItem2.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                setVisible(false);
                jFrame3.setVisible(true);
            }
        });

        jMenuItem7.setText("删改学员");
        jMenu4.add(jMenuItem7);
        jMenuItem7.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                jPanel2.setVisible(false);
                jPanel4.setVisible(true);
                jPanel5.setVisible(false);
                jPanel3.setVisible(false);
            }
        });

        jMenu1.add(jMenu4);

        jMenuItem1.setText("成绩查询");
        jMenu1.add(jMenuItem1);
        jMenuItem1.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                List<Student> list = adminDao.selectAllStudent();
                DefaultListModel dlm=new DefaultListModel();
                for (Student student : list) {
                    dlm.addElement(student.getName());
                }
                jList1.setModel(dlm);
                jPanel2.setVisible(true);
                jPanel4.setVisible(false);
                jPanel5.setVisible(false);
                jPanel3.setVisible(false);
            }
        });

        jMenuBar1.add(jMenu1);

        jMenu2.setText("导师管理");
        jMenu2.setPreferredSize(new java.awt.Dimension(74, 30));

        jMenuItem10.setText("试题管理");
        jMenuItem10.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                jPanel5.setVisible(true);
                jPanel2.setVisible(false);
                jPanel3.setVisible(false);
                jPanel4.setVisible(false);
            }
        });






        jMenu2.add(jMenuItem10);

        jMenu7.setText("科目管理");
        jMenu2.add(jMenu7);

        jMenuItem4.setText("增加科目");
        jMenu7.add(jMenuItem4);
        jMenuItem4.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                setVisible(false);
                jFrame4.setVisible(true);
            }
        });

        jMenuItem6.setText("删除科目");
        jMenu7.add(jMenuItem6);
        jMenuItem6.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                setVisible(false);
                jFrame8.setVisible(true);
            }
        });

        jMenuItem9.setText("更改密码");
        jMenu2.add(jMenuItem9);
        jMenuItem9.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                setVisible(false);
                jFrame6.setVisible(true);
            }
        });

        jMenuItem8.setText("退出登陆");
        jMenu2.add(jMenuItem8);
        jMenuItem8.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                dispose();
                Login.loginwin.setVisible(true);
            }
        });



        jMenuBar1.add(jMenu2);




        setJMenuBar(jMenuBar1);

        GroupLayout layout = new GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addGap(0, 533, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                .addComponent(jPanel2, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                        .addContainerGap(8, Short.MAX_VALUE)
                                        .addComponent(jPanel3, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addContainerGap(8, Short.MAX_VALUE)))
                        .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                        .addContainerGap()
                                        .addComponent(jPanel4, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addContainerGap()))
                        .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                        .addContainerGap()
                                        .addComponent(jPanel5, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(2, 2, 2)))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addGap(0, 355, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                .addComponent(jPanel2, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                        .addContainerGap(8, Short.MAX_VALUE)
                                        .addComponent(jPanel3, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addContainerGap(9, Short.MAX_VALUE)))
                        .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                        .addContainerGap()
                                        .addComponent(jPanel4, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addContainerGap()))
                        .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                        .addContainerGap()
                                        .addComponent(jPanel5, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(33, 33, 33)))
        );

        pack();
    }// </editor-fold>

    private void jTextField3ActionPerformed(ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void jTextField11ActionPerformed(ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void fixBattonActionPerformed(ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void delBattonActionPerformed(ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void jTextField15ActionPerformed(ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void jTextField19ActionPerformed(ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void jTextField20ActionPerformed(ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void fixBatton2ActionPerformed(ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void delBatton2ActionPerformed(ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void jTextField1ActionPerformed(ActionEvent evt) {
        // TODO add your handling code here:
    }


    public static void ManageStart() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (UIManager.LookAndFeelInfo info : UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Manage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Manage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Manage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Manage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                if (manage==null){
                    synchronized (Login.class) {
                        if (manage == null) {
                            manage = new Manage();
                            manage.setVisible(true);
                        }
                    }
                }else {
                    manage.setVisible(true);
                }
            }
        });
    }

    // Variables declaration - do not modify
    private JButton delBatton;
    private JButton delBatton2;
    private JButton fixBatton;
    private JButton fixBatton2;
    private JButton inquireBatton;
    private JButton inquireBatton2;
    private JButton jButton1;
    private JButton jButton11;
    private JButton jButton12;
    private JButton jButton13;
    private JButton jButton14;
    private JButton jButton17;
    private JButton jButton18;
    private JButton jButton19;
    private JButton jButton20;
    private JButton jButton4;
    private JButton jButton5;
    private JButton jButton8;
    private JButton jButton9;
    private JFileChooser jFileChooser1;
    private JFrame jFrame1;
    private JFrame jFrame2;
    private JFrame jFrame3;
    private JFrame jFrame4;
    private JFrame jFrame5;
    private JFrame jFrame6;
    private JFrame jFrame8;
    private JLabel jLabel1;
    private JLabel jLabel10;
    private JLabel jLabel11;
    private JLabel jLabel12;
    private JLabel jLabel13;
    private JLabel jLabel14;
    private JLabel jLabel15;
    private JLabel jLabel16;
    private JLabel jLabel17;
    private JLabel jLabel2;
    private JLabel jLabel20;
    private JLabel jLabel21;
    private JLabel jLabel22;
    private JLabel jLabel23;
    private JLabel jLabel24;
    private JLabel jLabel25;
    private JLabel jLabel28;
    private JLabel jLabel29;
    private JLabel jLabel3;
    private JLabel jLabel4;
    private JLabel jLabel5;
    private JLabel jLabel6;
    private JLabel jLabel7;
    private JLabel jLabel8;
    private JList<String> jList1;
    private JList<String> jList2;
    private JList<String> jList3;
    private JMenu jMenu1;
    private JMenu jMenu2;
    private JMenu jMenu4;
    private JMenu jMenu5;
    private JMenuItem jMenuItem10;
    private JMenu jMenu7;
    private JMenuBar jMenuBar1;
    private JMenuItem jMenuItem1;
    private JMenuItem jMenuItem2;
    private JMenuItem jMenuItem4;
    private JMenuItem jMenuItem6;
    private JMenuItem jMenuItem7;
    private JMenuItem jMenuItem8;
    private JMenuItem jMenuItem9;
    private JPanel jPanel2;
    private JPanel jPanel3;
    private JPanel jPanel4;
    private JPanel jPanel5;
    private JScrollPane jScrollPane1;
    private JScrollPane jScrollPane2;
    private JScrollPane jScrollPane4;
    private JScrollPane jScrollPane5;
    private JTextArea jTextArea1;
    private JTextArea jTextArea2;
    private JTextField jTextField1;
    private JTextField jTextField10;
    private JTextField jTextField11;
    private JTextField jTextField12;
    private JTextField jTextField13;
    private JTextField jTextField14;
    private JTextField jTextField15;
    private JTextField jTextField18;
    private JTextField jTextField19;
    private JTextField jTextField2;
    private JTextField jTextField20;
    private JTextField jTextField21;
    private JTextField jTextField23;
    private JTextField jTextField3;
    private JTextField jTextField4;
    private JTextField jTextField5;
    private JTextField nameInput;
    private JScrollPane studentShow;
    private JTextField subjectInput;
    // End of variables declaration

}
