package club.banyuan.view;

import club.banyuan.controller.CheckRegister;
import club.banyuan.dao.AdminDaoImpl;
import club.banyuan.service.Impl.AdminServerImpl;
import com.sun.tools.internal.ws.api.wsdl.TWSDLOperation;

import javax.swing.*;
import javax.swing.event.MenuEvent;
import javax.swing.event.MenuListener;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.Map;

public class StudentUI extends JFrame {

    AdminServerImpl adminServer = new AdminServerImpl();
    AdminDaoImpl adminDao = new AdminDaoImpl();

    /**
     * Creates new form 考试
     */
    public StudentUI() {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jFrame1 = new JFrame();
        jLabel1 = new JLabel();
        jTextField2 = new JTextField();
        userNameInput = new JTextField();
        jLabel3 = new JLabel();
        nameInput = new JTextField();
        jLabel4 = new JLabel();
        trueBatton = new JButton();
        quitBatton = new JButton();
        jLabel10 = new JLabel();
        jFrame6 = new JFrame();
        trueBatton1 = new JButton();
        quitBatton1 = new JButton();
        jLabel2 = new JLabel();
        newPasswordInput = new JTextField();
        jLabel7 = new JLabel();
        captcha = new JTextField();
        emailInput = new JTextField();
        jLabel8 = new JLabel();
        getCaptcha = new JButton();
        jLabel9 = new JLabel();
        jFrame2 = new JFrame();
        jFileChooser1 = new JFileChooser();
        jPanel1 = new JPanel();
        head = new JLabel();
        score = new JScrollPane();
        jTextArea1 = new JTextArea();
        testBegin = new JButton();
        jButton1 = new JButton();
        jPanel3 = new JPanel();
        jScrollPane3 = new JScrollPane();
        testShow = new JList<>();
        jScrollPane5 = new JScrollPane();
        scoreShow = new JTextArea();
        jMenuBar1 = new JMenuBar();
        home = new JMenu();
        getScore = new JMenu();
        jMenu3 = new JMenu();
        changeMassage = new JMenuItem();
        changePassword = new JMenuItem();
        quit = new JMenuItem();

        jPanel1.setVisible(true);
        jPanel3.setVisible(false);

        jLabel1.setText("ID:");

        jTextField2.setEnabled(false);

        userNameInput.setText(Login.uName);
        userNameInput.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                userNameInputActionPerformed(evt);
            }
        });

        jLabel3.setText("用户名：");

        nameInput.setText(Login.strueName);

        jLabel4.setText("姓  名：");

        trueBatton.setText("确认");
        trueBatton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {

            }
        });

        quitBatton.setText("取消");

        jLabel10.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jLabel10.setHorizontalAlignment(SwingConstants.CENTER);
        jLabel10.setText("修改信息");

        jFrame1.setSize(321, 359);
        jFrame1.setLocationRelativeTo(null);
        jFrame1.setResizable(false);
        jFrame2.setSize(562, 412);
        jFrame2.setLocationRelativeTo(null);
        jFrame2.setResizable(false);
        jFrame6.setSize(364, 296);
        jFrame6.setLocationRelativeTo(null);
        jFrame6.setResizable(false);

        GroupLayout jFrame1Layout = new GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
                jFrame1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addGroup(GroupLayout.Alignment.TRAILING, jFrame1Layout.createSequentialGroup()
                                .addContainerGap(64, Short.MAX_VALUE)
                                .addGroup(jFrame1Layout.createParallelGroup(GroupLayout.Alignment.TRAILING)
                                        .addGroup(jFrame1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                                .addGroup(jFrame1Layout.createSequentialGroup()
                                                        .addComponent(jLabel1)
                                                        .addGap(48, 48, 48)
                                                        .addComponent(jTextField2, GroupLayout.PREFERRED_SIZE, 136, GroupLayout.PREFERRED_SIZE))
                                                .addGroup(jFrame1Layout.createSequentialGroup()
                                                        .addComponent(trueBatton)
                                                        .addGap(43, 43, 43)
                                                        .addComponent(quitBatton)))
                                        .addGroup(jFrame1Layout.createSequentialGroup()
                                                .addGroup(jFrame1Layout.createParallelGroup(GroupLayout.Alignment.TRAILING)
                                                        .addGroup(jFrame1Layout.createSequentialGroup()
                                                                .addComponent(jLabel3)
                                                                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                                                                .addComponent(userNameInput, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(jFrame1Layout.createSequentialGroup()
                                                                .addComponent(jLabel4)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(nameInput, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)))
                                                .addGap(2, 2, 2)))
                                .addGap(54, 54, 54))
                        .addGroup(jFrame1Layout.createSequentialGroup()
                                .addGap(88, 88, 88)
                                .addComponent(jLabel10, GroupLayout.PREFERRED_SIZE, 145, GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jFrame1Layout.linkSize(SwingConstants.HORIZONTAL, new java.awt.Component[]{jTextField2, nameInput, userNameInput});

        jFrame1Layout.setVerticalGroup(
                jFrame1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addGroup(GroupLayout.Alignment.TRAILING, jFrame1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel10, GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jFrame1Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel1)
                                        .addComponent(jTextField2, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                                .addGap(31, 31, 31)
                                .addGroup(jFrame1Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel3)
                                        .addComponent(userNameInput, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                                .addGap(31, 31, 31)
                                .addGroup(jFrame1Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel4)
                                        .addComponent(nameInput, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                                .addGap(52, 52, 52)
                                .addGroup(jFrame1Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                        .addComponent(trueBatton)
                                        .addComponent(quitBatton))
                                .addGap(27, 27, 27))
        );

        trueBatton1.setText("确认");

        quitBatton1.setText("取消");

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        jLabel2.setHorizontalAlignment(SwingConstants.CENTER);
        jLabel2.setText("新密码：");

        newPasswordInput.setText("");
        newPasswordInput.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                newPasswordInputActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        jLabel7.setHorizontalAlignment(SwingConstants.CENTER);
        jLabel7.setText("验证码：");

        captcha.setText("");
        captcha.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                captchaActionPerformed(evt);
            }
        });

        emailInput.setText("");
        emailInput.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                emailInputActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        jLabel8.setHorizontalAlignment(SwingConstants.CENTER);
        jLabel8.setText("邮箱：");

        getCaptcha.setText("获取验证码");

        jLabel9.setFont(new java.awt.Font("Lucida Grande", 0, 22)); // NOI18N
        jLabel9.setHorizontalAlignment(SwingConstants.CENTER);
        jLabel9.setText("更改密码");

        GroupLayout jFrame6Layout = new GroupLayout(jFrame6.getContentPane());
        jFrame6.getContentPane().setLayout(jFrame6Layout);
        jFrame6Layout.setHorizontalGroup(
                jFrame6Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addGroup(jFrame6Layout.createSequentialGroup()
                                .addGap(54, 54, 54)
                                .addGroup(jFrame6Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                        .addGroup(jFrame6Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                                .addGroup(GroupLayout.Alignment.TRAILING, jFrame6Layout.createSequentialGroup()
                                                        .addComponent(jLabel2, GroupLayout.PREFERRED_SIZE, 83, GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                                                        .addComponent(newPasswordInput, GroupLayout.PREFERRED_SIZE, 168, GroupLayout.PREFERRED_SIZE))
                                                .addGroup(jFrame6Layout.createSequentialGroup()
                                                        .addComponent(jLabel7, GroupLayout.PREFERRED_SIZE, 83, GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                                                        .addComponent(captcha, GroupLayout.PREFERRED_SIZE, 168, GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(jFrame6Layout.createParallelGroup(GroupLayout.Alignment.TRAILING)
                                                .addComponent(getCaptcha, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addGroup(jFrame6Layout.createSequentialGroup()
                                                        .addComponent(jLabel8, GroupLayout.PREFERRED_SIZE, 83, GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                                                        .addComponent(emailInput, GroupLayout.PREFERRED_SIZE, 168, GroupLayout.PREFERRED_SIZE))))
                                .addGap(47, 47, 47))
                        .addGroup(GroupLayout.Alignment.TRAILING, jFrame6Layout.createSequentialGroup()
                                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jFrame6Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                        .addGroup(GroupLayout.Alignment.TRAILING, jFrame6Layout.createSequentialGroup()
                                                .addComponent(trueBatton1)
                                                .addGap(43, 43, 43)
                                                .addComponent(quitBatton1)
                                                .addGap(80, 80, 80))
                                        .addGroup(GroupLayout.Alignment.TRAILING, jFrame6Layout.createSequentialGroup()
                                                .addComponent(jLabel9, GroupLayout.PREFERRED_SIZE, 155, GroupLayout.PREFERRED_SIZE)
                                                .addGap(99, 99, 99))))
        );
        jFrame6Layout.setVerticalGroup(
                jFrame6Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addGroup(GroupLayout.Alignment.TRAILING, jFrame6Layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addComponent(jLabel9, GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addGroup(jFrame6Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                        .addComponent(emailInput, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel8))
                                .addGap(7, 7, 7)
                                .addComponent(getCaptcha)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jFrame6Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                        .addComponent(captcha, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel7))
                                .addGap(18, 18, 18)
                                .addGroup(jFrame6Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                        .addComponent(newPasswordInput, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel2))
                                .addGap(18, 18, 18)
                                .addGroup(jFrame6Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                        .addComponent(trueBatton1)
                                        .addComponent(quitBatton1))
                                .addGap(29, 29, 29))
        );

        GroupLayout jFrame2Layout = new GroupLayout(jFrame2.getContentPane());
        jFrame2.getContentPane().setLayout(jFrame2Layout);
        jFrame2Layout.setHorizontalGroup(
                jFrame2Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addGroup(jFrame2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jFileChooser1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jFrame2Layout.setVerticalGroup(
                jFrame2Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addGroup(jFrame2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jFileChooser1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);

        head.setText(  Login.strueName);
        head.setFont(new Font("宋体",Font.BOLD,40));
        jTextArea1.setEditable(false);
        jTextArea1.setFont(new Font("宋体",Font.BOLD,100));
        jTextArea1.setText("牛" + "\n" + "逼");
        jTextArea1.setColumns(20);
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(5);
        score.setViewportView(jTextArea1);

        testBegin.setText("开始考试");
        testBegin.addActionListener(new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e) {
                TestReady.start();
                setVisible(false);
            }
        });

        jButton1.setText("更换头像");

        GroupLayout jPanel1Layout = new GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(37, 37, 37)
                                                .addComponent(head, GroupLayout.PREFERRED_SIZE, 175, GroupLayout.PREFERRED_SIZE)
                                                .addGap(30, 30, 30))
                                        .addGroup(GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                .addContainerGap()
                                                .addComponent(jButton1)
                                                .addGap(71, 71, 71)))
                                .addComponent(score, GroupLayout.PREFERRED_SIZE, 231, GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(73, Short.MAX_VALUE))
                        .addGroup(GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(testBegin, GroupLayout.PREFERRED_SIZE, 110, GroupLayout.PREFERRED_SIZE)
                                .addGap(216, 216, 216))
        );
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(36, 36, 36)
                                                .addComponent(score, GroupLayout.PREFERRED_SIZE, 243, GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(74, 74, 74)
                                                .addComponent(head, GroupLayout.PREFERRED_SIZE, 158, GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(jButton1)))
                                .addGap(18, 18, 18)
                                .addComponent(testBegin, GroupLayout.PREFERRED_SIZE, 38, GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(16, Short.MAX_VALUE))
        );

        testShow.setModel(new AbstractListModel<String>() {
            String[] strings = {};

            public int getSize() {
                return strings.length;
            }

            public String getElementAt(int i) {
                return strings[i];
            }
        });
        jScrollPane3.setViewportView(testShow);

        scoreShow.setEditable(false);
        scoreShow.setColumns(20);
        scoreShow.setLineWrap(true);
        scoreShow.setRows(5);
        scoreShow.setText("分数");
        scoreShow.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jScrollPane5.setViewportView(scoreShow);

        GroupLayout jPanel3Layout = new GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
                jPanel3Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addComponent(jScrollPane3, GroupLayout.PREFERRED_SIZE, 257, GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                                .addComponent(jScrollPane5, GroupLayout.PREFERRED_SIZE, 198, GroupLayout.PREFERRED_SIZE)
                                .addGap(31, 31, 31))
        );
        jPanel3Layout.setVerticalGroup(
                jPanel3Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addGroup(GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addContainerGap(40, Short.MAX_VALUE)
                                .addGroup(jPanel3Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                        .addComponent(jScrollPane5, GroupLayout.PREFERRED_SIZE, 257, GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jScrollPane3, GroupLayout.PREFERRED_SIZE, 276, GroupLayout.PREFERRED_SIZE))
                                .addGap(35, 35, 35))
        );

        jPanel3Layout.linkSize(SwingConstants.VERTICAL, new java.awt.Component[]{jScrollPane3, jScrollPane5});

        jMenuBar1.setSize(new java.awt.Dimension(86, 30));
        setJMenuBar(jMenuBar1);
        home.setText("首页");
        jMenuBar1.add(home);

        home.addMenuListener(new MenuListener() {
            @Override
            public void menuSelected(MenuEvent e) {
                jPanel1.setVisible(true);
                jPanel3.setVisible(false);
            }

            @Override
            public void menuDeselected(MenuEvent e) {

            }

            @Override
            public void menuCanceled(MenuEvent e) {

            }
        });

        getScore.setText("查询成绩");
        getScore.setPreferredSize(new java.awt.Dimension(74, 30));
        jMenuBar1.add(getScore);

        getScore.addMenuListener(new MenuListener() {
            @Override
            public void menuSelected(MenuEvent e) {
                jPanel1.setVisible(false);
                jPanel3.setVisible(true);
                    scoreShow.setText("您尚未参加考试");

                    DefaultListModel dlm=new DefaultListModel();
                    int countA = 0;
                    int countB = 0;
                    int point = 0;
                for (Map.Entry<Integer, String> integerStringEntry : TestSingle.mapSingleAnswer.entrySet()) {
                    String judge;
                    if(adminServer.parseOptToInt(integerStringEntry.getValue()).equals(TestSingle.trueAnswer.get(countA))){
                    judge  = "正确!";
                    point++;
                    }else {
                        judge = "错误～";
                    }
                    dlm.addElement("你的选项: " + integerStringEntry.getValue() + " 正确答案: " + adminServer.parseOpt(TestSingle.trueAnswer.get(countA++)) + "  " +  judge);
                }
                for (Map.Entry<Integer, String> integerStringEntry : TestMultiple.mapMultipleAnswer.entrySet()) {
                    String judge;
                    if(adminServer.parseOptToInt(integerStringEntry.getValue()).equals(TestMultiple.trueAnswerM.get(countB))){
                        judge  = "正确!";
                        point++;
                    }else {
                        judge = "错误～";
                    }
                    dlm.addElement("你的选项: " + integerStringEntry.getValue() + " 正确答案: " + adminServer.parseOpt(TestMultiple.trueAnswerM.get(countB++)) + "  " +  judge);
                }
                    testShow.setModel(dlm);
                scoreShow.setFont(new Font("宋体",Font.BOLD,30));
                scoreShow.setText("总成绩:" + "\n" + "     " + point*10);
                }

            @Override
            public void menuDeselected(MenuEvent e) {

            }

            @Override
            public void menuCanceled(MenuEvent e) {

            }
        });

        jMenu3.setText("个人管理");
        jMenuBar1.add(jMenu3);
        jMenu3.setPreferredSize(new java.awt.Dimension(74, 30));

        changeMassage.setText("更改信息");
        jMenu3.add(changeMassage);
        changeMassage.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                jFrame1.setVisible(true);
                setVisible(false);
            }
        });
        //更改信息界面取消按钮事件
        quitBatton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                jFrame1.setVisible(false);
                setVisible(true);
            }
        });
        //更改信息界面确认按钮事件
        trueBatton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {

                if (CheckRegister.checkUserName(userNameInput.getText()) == true && CheckRegister.checkName(nameInput.getText()) == true) {
                    adminDao.updateStudentByName(userNameInput.getText(),nameInput.getText(),Login.uName);
                    jFrame1.setVisible(false);
                    setVisible(true);//-------------------------保存
                } else {
                    JOptionPane.showMessageDialog(new JLabel(), "用户名或姓名格式错误");
                }
            }
        });


        changePassword.setText("更改密码");
        jMenu3.add(changePassword);
        changePassword.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                jFrame6.setVisible(true);
                setVisible(false);
            }
        });

        //更改密码取消按钮事件
        quitBatton1.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                jFrame6.setVisible(false);
                setVisible(true);
            }
        });

        ////更改密码确认按钮事件
        trueBatton1.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                if (CheckRegister.checkPwd(newPasswordInput.getText()) == true) {           //-------------------------------验证码没有
                    adminDao.updateStudentPwdByName(newPasswordInput.getText(),Login.uName);
                    jFrame6.setVisible(false);
                    setVisible(true);
                } else {
                    JOptionPane.showMessageDialog(new JLabel(), "验证码或密码格式错误");
                }
            }
        });
        //邮箱验证码事件
        getCaptcha.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {

            }
        });


        quit.setText("退出登录");
        jMenu3.add(quit);
        quit.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                dispose();
                Login.loginwin.setVisible(true);
            }
        });

        GroupLayout layout = new GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addGap(0, 558, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(jPanel1, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(6, 6, 6)))
                        .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                        .addContainerGap()
                                        .addComponent(jPanel3, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addContainerGap()))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addGap(0, 366, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(jPanel1, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(6, 6, 6)))
                        .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                        .addContainerGap()
                                        .addComponent(jPanel3, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(21, 21, 21)))
        );

        pack();
    }// </editor-fold>

    private void userNameInputActionPerformed(ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void newPasswordInputActionPerformed(ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void changeMassageActionPerformed(ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void captchaActionPerformed(ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void emailInputActionPerformed(ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void testBeginActionPerformed(ActionEvent evt) {
        // TODO add your handling code here:
    }

    /**
     */
    public static void stuStart() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (UIManager.LookAndFeelInfo info : UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StudentUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify
    private JTextField captcha;
    private JMenuItem changeMassage;
    private JMenuItem changePassword;
    private JTextField emailInput;
    private JButton getCaptcha;
    private JMenu getScore;
    private JMenu havana;
    private JLabel head;
    private JMenu home;
    private JButton jButton1;
    private JFileChooser jFileChooser1;
    private JFrame jFrame1;//修改信息
    private JFrame jFrame2;//文件选择器
    private JFrame jFrame6;//更改密码
    private JLabel jLabel1;
    private JLabel jLabel10;
    private JLabel jLabel2;
    private JLabel jLabel3;
    private JLabel jLabel4;
    private JLabel jLabel7;
    private JLabel jLabel8;
    private JLabel jLabel9;
    private JMenu jMenu3;
    private JMenuBar jMenuBar1;
    private JPanel jPanel1;
    private JPanel jPanel3;
    private JScrollPane jScrollPane3;
    private JScrollPane jScrollPane5;
    private JTextArea jTextArea1;
    private JTextField jTextField2;
    private JTextField nameInput;
    private JTextField newPasswordInput;
    private JMenuItem quit;
    private JButton quitBatton;
    private JButton quitBatton1;
    private JScrollPane score;
    private JTextArea scoreShow;
    private JButton testBegin;
    private JList<String> testShow;
    private JButton trueBatton;
    private JButton trueBatton1;
    private JTextField userNameInput;
    // End of variables declaration
}
